version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql_injection_target
    ports:
      - "8086:80"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: password  # MySQL root 密码
      MYSQL_DATABASE: vidar  # 创建的数据库
      MYSQL_USER: user  # 创建的数据库用户
      MYSQL_PASSWORD: pass  # 数据库用户密码
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
